### ISSUE TITLE
When running gulp watch with Elixir it is not starting browsersync

### ISSUE THREAD

**Issue by simonj** [anheru88/laravel-elixir-browser-sync2#1]
Hey,

Thanks for a nice lib.
I have installed your plugin and it works fine if i run "gulp" in my terminal. but and it refresh right.
But is does not recompile my scripts.

my package.js is this

```
"laravel-elixir": "*",
"laravel-elixir-browsersync2": "^0.1.0",
```

and my browsersync in my .mix function is this

```
BrowserSync.init();
mix.BrowserSync([
    'app/**/*', 'public/**/*', 'resources/views/**/*'
],
    {
        proxy           : process.env.LOCAL_URL,
        logPrefix       : "Laravel Eixir BrowserSync",
        logConnections  : false,
        reloadOnRestart : true,
        notify          : false,
        files: ['app/**/*', 'public/**/*', 'resources/**/*']
    });
```

**Comment by anheru88** [comment]
Hi  @SimonJ, yes sr, right now the plugin, can run only using watch, i try to fix this problem soon, but i don't now why not found, sorry for this.

**Comment by simonj** [comment]
Thanks for your reply @anheru88 :)

**Comment by simonj** [comment]
maybe you can see what this plugin does https://github.com/ponko2/laravel-elixir-browser-sync its recompile fine :)
